version: "3"

services:
  php-fpm:
    build:
      context: ./docker-configs/php-fpm
      args:
        - DATE_TIMEZONE=${PHP_FPM_DATE_TIMEZONE}
    volumes:
      - ./application:/cookbook
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  workspace:
    build:
      context: ./docker-configs/workspace
      args:
        - DATE_TIMEZONE=${WORKSPACE_DATE_TIMEZONE}
        - USER_UID=${WORKSPACE_USER_UID}
        - USER_GID=${WORKSPACE_USER_GID}
    environment:
      - TZ=${WORKSPACE_DATE_TIMEZONE}
    volumes:
      - ./application:/cookbook
    networks:
      - backend

    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  mariadb:
    image: mariadb:10.2
    environment:
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    volumes:
      - ./docker-configs/mariadb/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - mariadb-data:/var/lib/mysql
    networks:
      - backend

  nginx:
    image: nginx:1.12
    environment:
      - TZ=${NGINX_TIMEZONE}
    volumes:
      - ./application:/cookbook
      - ./logs/nginx/:/var/log/nginx
      - ./docker-configs/nginx/app.conf:/etc/nginx/conf.d/app.conf
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
    depends_on:
      - php-fpm
    networks:
      - frontend
      - backend

networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"

volumes:
  mariadb-data: